joint_limits:
  joint_limits:
    base_x:
      has_position_limits: true
      min_position: -10.0
      max_position: 10.0
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    base_y:
      has_position_limits: true
      min_position: -10.0
      max_position: 10.0
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    base_theta:
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    joint_shoulder:
      has_position_limits: true
      min_position: -0.523599
      max_position: 2.617994
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    joint_elbow:
      has_position_limits: true
      min_position: -0.610865
      max_position: 2.530727
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    joint_wrist:
      has_position_limits: true
      min_position: -1.570796
      max_position: 1.570796
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    joint_hand:
      has_position_limits: true
      min_position: -1.22173
      max_position: 1.396263
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    joint_grip_L:
      has_position_limits: true
      min_position: -1.570796
      max_position: 0.0
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
    joint_grip_R:
      has_position_limits: true
      min_position: 0.0
      max_position: 1.570796
      has_velocity_limits: true
      max_velocity: 1
      has_acceleration_limits: false
