trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - base_arm_controller
    - arm_controller
    - gripper_controller

  base_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_x
      - base_y
      - base_theta
      - JointFrame
      - JointTelescope
      - JointArm1
      - JointArm2
      - JointWrist
      - JointHand

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - JointArm1
      - JointArm2
      - JointHand
      - JointTelescope
      - JointWrist

  gripper_controller:
    type: GripperCommand
    action_ns: gripper_cmd
    default: false
    joints:
      - JointFingerL
      - JointFingerR
