planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
    default_planner_request_adapters/AddTimeOptimalParameterization
    default_planner_request_adapters/ResolveConstraintFrames
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints

# Configure planning pipelines
planning_pipelines:
  - ompl
default_planning_pipeline: ompl

arm:
  planner_configs:
    - BiRRTstar
    - RRTstar
    - RRTConnect
  projection_evaluator: joints(JointFrame,JointTelescope)
  longest_valid_segment_fraction: 0.005

gripper:
  planner_configs:
    - RRTConnect
    - RRTstar
  longest_valid_segment_fraction: 0.01
