trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

trajectory_processing:
  time_parameterization:
    algorithm: "time_optimal_trajectory_generation"
    max_velocity_scaling_factor: 0.1
    max_acceleration_scaling_factor: 0.05
    path_tolerance: 0.1
    resample_dt: 0.1
    min_angle_change: 0.001
    smoothing_velocity_tolerance: 0.01
    use_smoothing: true
